<?php
declare(strict_types=1);

// FakeJson SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

FakeJsonUtility::setRegistrar(function (FakeJsonUtility $u): void {
    $u->clean = [FakeJsonClean::class, 'call'];
    $u->done = [FakeJsonDone::class, 'call'];
    $u->make_error = [FakeJsonMakeError::class, 'call'];
    $u->feature_add = [FakeJsonFeatureAdd::class, 'call'];
    $u->feature_hook = [FakeJsonFeatureHook::class, 'call'];
    $u->feature_init = [FakeJsonFeatureInit::class, 'call'];
    $u->fetcher = [FakeJsonFetcher::class, 'call'];
    $u->make_fetch_def = [FakeJsonMakeFetchDef::class, 'call'];
    $u->make_context = [FakeJsonMakeContext::class, 'call'];
    $u->make_options = [FakeJsonMakeOptions::class, 'call'];
    $u->make_request = [FakeJsonMakeRequest::class, 'call'];
    $u->make_response = [FakeJsonMakeResponse::class, 'call'];
    $u->make_result = [FakeJsonMakeResult::class, 'call'];
    $u->make_point = [FakeJsonMakePoint::class, 'call'];
    $u->make_spec = [FakeJsonMakeSpec::class, 'call'];
    $u->make_url = [FakeJsonMakeUrl::class, 'call'];
    $u->param = [FakeJsonParam::class, 'call'];
    $u->prepare_auth = [FakeJsonPrepareAuth::class, 'call'];
    $u->prepare_body = [FakeJsonPrepareBody::class, 'call'];
    $u->prepare_headers = [FakeJsonPrepareHeaders::class, 'call'];
    $u->prepare_method = [FakeJsonPrepareMethod::class, 'call'];
    $u->prepare_params = [FakeJsonPrepareParams::class, 'call'];
    $u->prepare_path = [FakeJsonPreparePath::class, 'call'];
    $u->prepare_query = [FakeJsonPrepareQuery::class, 'call'];
    $u->graphql_body = [FakeJsonGraphql::class, 'body'];
    $u->graphql_errors = [FakeJsonGraphql::class, 'errors'];
    $u->result_basic = [FakeJsonResultBasic::class, 'call'];
    $u->result_body = [FakeJsonResultBody::class, 'call'];
    $u->result_headers = [FakeJsonResultHeaders::class, 'call'];
    $u->transform_request = [FakeJsonTransformRequest::class, 'call'];
    $u->transform_response = [FakeJsonTransformResponse::class, 'call'];
});
